name: NUMERO

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest # ejecuta sobre este sistema operativo

    steps:
      - uses: actions/checkout@v2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v1 #importante el uso del v1 al final
        env:
          TEST_NAME: numeroTest #Nombre del test
        with:
          configuration: test/phpunit.xml
          args: --coverage-text
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker Login      #Esto son los secretos de usuario y de password.
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/numerocicd:${{ github.sha }} .
          docker build -t ${{ secrets.DOCKER_USER }}/numerocicd:latest .
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/numerocicd:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/numerocicd:latest    